version: '3.8'

services:
  postgres:
    image: debezium/postgres:14-alpine
    restart: unless-stopped
    container_name: postgres_voz_da_populacao
    environment:
      - POSTGRES_USER=app_voz
      - POSTGRES_PASSWORD=app_voz
      - POSTGRES_DB=voz_populacao
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_voz -d voz_da_populacao" ]
      interval: 2s
      timeout: 3s
      retries: 30
    volumes:
      - postgres:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:16.1.1
    restart: on-failure
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=voz_da_populacao
      - DB_USER=app_voz
      - DB_PASSWORD=app_voz
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
    ports:
      - "28081:8080"
    depends_on:
      - postgres

volumes:
  postgres: { }
  keycloak: { }