version: '3.8'

services:
  postgres:
    image: debezium/postgres:14-alpine
    restart: unless-stopped
    container_name: postgres_voz_da_populacao
    environment:
      - POSTGRES_USER=app_voz
      - POSTGRES_PASSWORD=app_voz
      - POSTGRES_DB=voz_populacao
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_voz -d voz_da_populacao" ]
      interval: 2s
      timeout: 3s
      retries: 30
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: { }
  keycloak: { }